# Generated by Django 4.1.3 on 2022-11-21 19:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/imgCarrusel')),
            ],
        ),
        migrations.CreateModel(
            name='Expre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inicio', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.FileField(default=None, upload_to='static/img/expres')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('', ''), ('Robótica', 'Robótica'), ('Herramientas', 'Herramientas'), ('Cables, accesorios e insumos', 'Cables, accesorios e insumos')], default=None, max_length=50)),
                ('imagen', models.FileField(default=None, upload_to='static/img/productos')),
            ],
        ),
    ]
