# Generated by Django 4.1.2 on 2022-11-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=None, upload_to='static/img/productos'),
        ),
    ]
