# Generated by Django 4.1.2 on 2022-12-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='static/img/prueba'),
        ),
    ]
