# Generated by Django 4.1.2 on 2022-11-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=15),
        ),
    ]
