# Generated by Django 4.1.2 on 2022-11-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
