# Generated by Django 4.1.2 on 2022-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='status',
        ),
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('Robótica', 'Robótica'), ('Robótica', 'Robótica'), ('asd', 'asd')], default=None, max_length=15),
        ),
    ]
