# Generated by Django 4.1.2 on 2022-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_carrusel'),
        ('home', '0005_remove_producto_status_producto_category'),
    ]

    operations = [
    ]
