# Generated by Django 4.1.2 on 2022-11-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_producto_category_alter_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagenes', models.FileField(default=None, upload_to='static/img/cursos')),
                ('horario', models.TextField()),
                ('inicio', models.TextField()),
                ('inscripcion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mensualidad', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('caracteristicas', models.TextField()),
                ('imagen', models.FileField(default=None, upload_to='static/img/modulos')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.curso')),
            ],
        ),
    ]
