# Generated by Django 4.1.2 on 2022-11-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_curso_modulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='imagenes',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='comentario',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='mensualidad',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='caracteristicas',
        ),
    ]
