# Generated by Django 4.1.2 on 2022-11-21 05:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_imagenes_curso_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
